using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using CP_Sight.Core.Models;

namespace CP_Sight.Web.Services;

/// <summary>
/// PDF report generator for CP-sight analysis results
/// </summary>
public class ReportGenerator
{
    public ReportGenerator()
    {
        // Configure QuestPDF license (Community for open source)
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public async Task<byte[]> GeneratePdfAsync(AnalysisResult result)
    {
        var document = Document.Create(container =>
        {
            container
                .Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);
                    page.DefaultTextStyle(x => x.FontSize(11));

                    // Header
                    page.Header()
                        .Text("CP-sight Analysis Report")
                        .SemiBold().FontSize(20).FontColor(Colors.Blue.Darken2);

                    // Content
                    page.Content()
                        .PaddingVertical(1, Unit.Centimetre)
                        .Column(col =>
                        {
                            // Patient Info Section
                            col.Item().Element(container => CreatePatientInfoSection(container, result));
                            
                            // Risk Assessment Section
                            col.Item().Element(container => CreateRiskSection(container, result));
                            
                            // Features Section
                            col.Item().Element(container => CreateFeaturesSection(container, result));
                            
                            // Recommendations Section
                            col.Item().Element(container => CreateRecommendationsSection(container, result));
                            
                            // Disclaimer
                            col.Item().PaddingTop(20).Text(GenerateDisclaimer())
                                .FontSize(9).FontColor(Colors.Grey.Darken1);
                        });

                    // Footer
                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Generated by CP-sight on ");
                            x.Span(DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm UTC"));
                        });
                });
        });

        return await Task.FromResult(document.GeneratePdf());
    }

    private void CreatePatientInfoSection(ColumnDescriptor container, AnalysisResult result)
    {
        container
            .Item()
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(10)
            .Column(col =>
            {
                col.Item().Text("Patient Information").SemiBold().FontSize(14);
                col.Item().PaddingTop(5).Row(row =>
                {
                    row.RelativeItem().Text($"Age: {result.InfantInfo.AgeWeeks} weeks");
                    row.RelativeItem().Text($"Corrected Age: {result.InfantInfo.CorrectedAgeWeeks?.ToString() ?? "N/A"} weeks");
                });
                col.Item().Row(row =>
                {
                    row.RelativeItem().Text($"Preterm: {(result.InfantInfo.IsPreterm ? "Yes" : "No")}");
                    row.RelativeItem().Text($"GA at Birth: {result.InfantInfo.GestationalAgeAtBirth?.ToString() ?? "N/A"} weeks");
                });
                col.Item().PaddingTop(5).Text($"Analysis ID: {result.Id}");
                col.Item().Text($"Analysis Date: {result.Timestamp:yyyy-MM-dd HH:mm UTC}");
            });
    }

    private void CreateRiskSection(ColumnDescriptor container, AnalysisResult result)
    {
        var riskColor = result.Assessment.OverallRisk switch
        {
            "low" => Colors.Green.Darken2,
            "medium" => Colors.Orange.Darken2,
            "high" => Colors.Red.Darken2,
            _ => Colors.Grey.Darken2
        };

        container
            .Item()
            .PaddingTop(15)
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(10)
            .Column(col =>
            {
                col.Item().Text("Risk Assessment").SemiBold().FontSize(14);
                
                col.Item().PaddingTop(10).Row(row =>
                {
                    row.RelativeItem().Text("Overall Risk Level:").SemiBold();
                    row.ConstantItem(100).Text(result.Assessment.OverallRisk.ToUpper())
                        .SemiBold().FontColor(riskColor);
                });
                
                col.Item().Row(row =>
                {
                    row.RelativeItem().Text("Risk Score:");
                    row.ConstantItem(100).Text($"{result.Assessment.RiskScore}/100");
                });
                
                col.Item().Row(row =>
                {
                    row.RelativeItem().Text("Confidence:");
                    row.ConstantItem(100).Text($"{result.Assessment.Confidence:P0}");
                });
                
                col.Item().Row(row =>
                {
                    row.RelativeItem().Text("Follow-up Required:");
                    row.ConstantItem(100).Text(result.Assessment.FollowUpRequired ? "Yes" : "No");
                });
            });
    }

    private void CreateFeaturesSection(ColumnDescriptor container, AnalysisResult result)
    {
        container
            .Item()
            .PaddingTop(15)
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(10)
            .Column(col =>
            {
                col.Item().Text("Movement Features Analysis").SemiBold().FontSize(14);
                
                col.Item().PaddingTop(10).Element(c => CreateFeatureRow(c, 
                    "Movement Complexity", result.Assessment.Breakdown.MovementComplexity));
                col.Item().Element(c => CreateFeatureRow(c, 
                    "Movement Variability", result.Assessment.Breakdown.MovementVariability));
                col.Item().Element(c => CreateFeatureRow(c, 
                    "Fidgety Movements", result.Assessment.Breakdown.FidgetyMovements));
                col.Item().Element(c => CreateFeatureRow(c, 
                    "Symmetry", result.Assessment.Breakdown.Symmetry));
            });
    }

    private void CreateFeatureRow(ColumnDescriptor container, string name, MovementFeatureStatus status)
    {
        var statusColor = status.Status switch
        {
            "normal" => Colors.Green.Darken2,
            "borderline" => Colors.Orange.Darken2,
            "abnormal" => Colors.Red.Darken2,
            _ => Colors.Grey.Darken2
        };

        container
            .Row(row =>
            {
                row.RelativeItem().Text(name);
                row.ConstantItem(60).Text($"{status.Value:F2}");
                row.ConstantItem(80).Text(status.Status.ToUpper())
                    .FontColor(statusColor).SemiBold();
            });
    }

    private void CreateRecommendationsSection(ColumnDescriptor container, AnalysisResult result)
    {
        container
            .Item()
            .PaddingTop(15)
            .Border(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(10)
            .Column(col =>
            {
                col.Item().Text("Recommendations").SemiBold().FontSize(14);
                
                foreach (var recommendation in result.Assessment.Recommendations)
                {
                    col.Item().PaddingTop(5).Row(row =>
                    {
                        row.ConstantItem(15).Text("•");
                        row.RelativeItem().Text(recommendation);
                    });
                }
            });
    }

    private string GenerateDisclaimer()
    {
        return "DISCLAIMER: This analysis is generated by an AI-based screening tool and is intended for research " +
               "and screening purposes only. It should not be used as the sole basis for clinical diagnosis. " +
               "All assessments should be validated by qualified healthcare professionals. CP-sight is not a " +
               "replacement for professional medical advice, diagnosis, or treatment.";
    }
}
